services:
    Google\Client:
        class: Google\Client
        calls:
            # Authentication with "API key"
            - [setDeveloperKey, ['getenv(GOOGLE_API_KEY)%']]
            # Authentication with "OAuth 2.0" using Client ID & Secret
            - [setClientId, ['getenv(GOOGLE_CLIENT_ID)%']]
            - [setClientSecret, ['getenv(GOOGLE_CLIENT_SECRET)%']]
            # Authentication with "OAuth 2.0" or "Service account" using JSON
            - [setAuthConfig, ['getenv(resolve:GOOGLE_AUTH_CONFIG)%']]
