knpu_oauth2_client:
    clients:
        google:
            type: google
            client_id: '${{ secrets.GOOGLE_CLIENT_ID }}'
            client_secret: '${{ secrets.GOOGLE_CLIENT_SECRET }}'
            redirect_route: connect_google_check
            redirect_params: {}