twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        publicationCategoryRepository: "@App\\Repository\\PublicationCategoryRepository"

when@test:
    twig:
        strict_variables: true
