twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        publicationCategoryRepository: "@App\\Repository\\PublicationCategoryRepository"
    cache: '%kernel.cache_dir%/twig'
    #cache: false

when@test:
    twig:
        strict_variables: true

when@dev:
    twig:
        cache: false
