runtime: custom
env: flex

runtime_config:
  document_root: public

env_variables:
  APP_ENV: prod
  DATABASE_URL: mysql://hubert:iqMF&@E889zQBcsr@34.155.222.100/scrilab


manual_scaling:
  instances: 1