version: "20.10.5"

services:
  database:
    image: mysql:8.0
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.4
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - database
    environment:
      PMA_HOST: database
    networks:
      - mynetwork

  app:
    image: a968b700aa36
    ports: 
      - "8080:80"
    networks:
      - mynetwork
    env_file:
      - ../.env
    environment:
      DATABASE_URL: mysql://root@database:3306/skl

networks:
  mynetwork:
    driver: bridge
