controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

live_component:
    resource: '@LiveComponentBundle/config/routes.php'

