queuekafka:
    # The type of your service (kafka), which uses the format
    # 'type:version'. Be sure to consult the Kafka documentation
    # (https://docs.platform.sh/add-services/kafka.html#supported-versions)
    # when choosing a version. If you specify a version number which is not available,
    # the CLI will return an error.
    type: kafka:3.2
    # The disk attribute is the size of the persistent disk (in MB) allocated to the service.
    disk: 512
