name: CD
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSHPASS: ${{ secrets.APP_PASS }}

    steps:
      - uses: actions/checkout@v2

      - name: APT_UPDATE and INSTALL SSHPASS
        run: sudo apt update && sudo apt install sshpass

      - name: Configure Git with access token
        run: git config --global url."https://${{ secrets.GIT_ACCESS_TOKEN }}:@github.com/".insteadOf "https://github.com/"

      - name: deploy
        run: sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.APP_USER }}@${{ secrets.APP_HOST }} "cd public_html/; git pull; composer install; npm run-script build; php bin/console cache:clear; php bin/console doctrine:migrations:migrate -n;"
