name: CD
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSHPASS: ${{ secrets.APP_PASS }}

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: APT_UPDATE and INSTALL SSHPASS
        run: sudo apt update && sudo apt install sshpass

      - name: Set up Node.js and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 20.7.0 # ou la version de votre choix
          cache: "npm"

      - name: Clear npm cache
        run: npm cache clean --force

      - name: deploy
        run: |
          sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.APP_USER }}@${{ secrets.APP_HOST }} \
          "cd applications/xfbbjgzbvt/public_html/ && \
          git config --local url.\"https://${{ secrets.GITHUB_TOKEN }}:@github.com/\".insteadOf \"https://github.com/\" && \
          git fetch && \
          git reset --hard origin/main && \
          sed -i 's/^GOOGLE_CLIENT_ID=.*/GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}/' .env.local
          sed -i 's/^GOOGLE_CLIENT_SECRET=.*/GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}/' .env.local
          sed -i 's/^CLOUDINARY_CLOUD_NAME=.*/CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}/' .env.local
          sed -i 's/^CLOUDINARY_API_KEY=.*/CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}/' .env.local
          sed -i 's/^CLOUDINARY_API_SECRET=.*/CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}/' .env.local
          sed -i 's/^API_HUBSPOT_SECRET=.*/API_HUBSPOT_SECRET=${{ secrets.API_HUBSPOT_SECRET }}/' .env.local
          composer install --no-scripts && \
          mkdir -p /tmp/npm-cache && \ # Créez un répertoire temporaire pour le cache npm
          npm config set "@fortawesome:registry" https://npm.fontawesome.com/ && \
          npm config set "//npm.fontawesome.com/:_authToken" ${{ secrets.FONTAWESOME_TOKEN }} && \
          npm install --cache /tmp/npm-cache && \ # Utilisez le nouveau répertoire temporaire pour le cache npm
          export PATH=./node_modules/.bin:$PATH && \
          php bin/console cache:clear && \
          php bin/console doctrine:migrations:migrate -n;"
